### ISSUE TITLE
Unexpected hifread when using debugger

### ISSUE THREAD

**Issue by ameirson** [bat52/cheap_pie#2]
When using debugger, stopping at breakpoints and during stepping, results in unexpected hifread. 
Example and details can be seen [here](https://drive.google.com/drive/folders/1_H_fgPtv9zUUWCKu77EZkhsxs4beYTzS?usp=share_link)

Analysis shows this is a result of debugger trying to read registers for display in "Variables" / "Locals" area. This yields the cp_register __repr__ function which results in a hifread if there is no "shadow" regval previous read.

To avoid unexpected hifread and to provide consistent behavior I suggest to replace the __repr__ implementation so that hifread is never performed even when a regval shadow doesnt yet exist.

An example of how the debugger "Variables" windows would look is attached.
 
![2023-05-12 17_26_17-test_cheap_pie – example py](https://github.com/bat52/cheap_pie/assets/72041929/d95d15f1-29f9-4d6b-81f0-81664a9cb41e)

**Comment by bat52** [comment]
Even though I have not been using the debugger myself in a while, I do recognize it might be useful sometimes.
I have verified the behavior, and confirm that the when debugging the script, the extra reads are there: even worse at every debugging 'step' all the registers of the hal are re-read, which can be annoying, especially for validation of big register files, for which access might not be that fast.

Yet, I do not like much your proposed solution of dropping entirely the __repr__ function, because I use a lot ipython, and it is VERY practical to simply write

hal.REGNAME

to read the register status.
I might still investigate to remove the hifread from the __repr__ function, and let it show just the bitifields without value, but...

My gut tells me a correct solution would pass by understanding why the debugger feels the urge to evaluate all registers values: I suspect this might correlate with the fact that I have implemented the cp_hal class to behave as an iterator.

This problem seriously challenges my python modjo.

**Comment by ameirson** [comment]
I have created a new cheap-pie fork with my suggested solution and also my ral_emu transport layer.
This is my first fork attempt, so any comments would be highly appreciated. 
The goal is to allow me to pip install this version which has my fix and my ral_emu transport.

**Comment by bat52** [comment]
Forking the code is probably the best option if you need a solution for your issue quickly.

However, long term I think it would probably be better trying to integrate a solution into the original repository so that we can share the coding efforts. For instance while investigating this I have much improved the test sequence, and I will commit the changes soon.

Regarding installing your fork with pip, you will need to create a pypi account, then you can create and test the package with the script `test_pypi.sh`, and generate the final pypi package with `pypi.sh`. However, I get that you are working with windows, so those scripts will not natively work: I advise installing WSL which works really well for me. Just, if you work on a directory shared between the linux machine and windows, stick with WSL1, because due to file access the python interpreter of WSL2 is VERY VERY slow.

**Comment by bat52** [comment]
I have just committed a change that fixes this issue.

The compromise I took was to remove the hifread from __repr__, so that now 
  hal.regs.REG
will show the register name and bitfields without the value, while
  hal.regs.REG.display()
will generate an hifread, and will report the values too.

This seems to avoid the spurious reads when debugging.

I had a quick look at your code, and I wonder why you did not merge the ral_emu files with cheap_pie. 
I would apply the following changes:

- move cp_reg_emu_transport.py under cheap_pie/transport
- move ipxact_dim_example.xml under cheap_pie/devices
- rename ral_emu.py to cp_ral_emu.py
- move cp_ral_emu.py to cheap_pie/cheap_pie_core
- rename example.py to ral_emu_example.py
- move ral_emu_example.py to test
- move emu_test.txt to test
- add all test functions of cp_ral_emu.py to /cheap_pie/cheap_pie_core/test.py

Once those changes are done (if you care), you can create a pull request for your code to be integrated in the original repo.
